- name: "0 - requested"
  color: "e5e5e5"
  description: "Issue has been created but not accepted. Issue may be closed if there is a duplicate."
- name: "0 - ordered"
  color: "e5e5e5"
  description: "Issue is not in progress."
- name: "1 - cooking"
  color: "e5e5e5"
  description: "Issue is in progress."
- name: "2 - taste testing"
  color: "e5e5e5"
  description: "Pull request is in review."
- name: "3 - done"
  color: "e5e5e5"
  description: "Pull request is completed and approved but not merged."
- name: "4 - out for delivery"
  color: "e5e5e5"
  description: "Pull request has been merged to resolve the issue."
- name: "5 - delivered"
  color: "e5e5e5"
  description: "Issue fix is deployed and resolved in production."
- name: "duplicate"
  color: "e5e5e5"
  description: "Issue is a duplicate."
