name: Sync labels
on: [workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: micnncim/action-label-syncer@v1
        with:
          manifest: .github/labels.yml
          repository: |
              craftastack/.github
              craftastack/appetizers
              craftastack/blog
              craftastack/craftastack
              craftastack/ingredients
              craftastack/toppings
          token: ${{ secrets.SYNC_LABELS }}
